image : maven:latest

stages:
    - build 
    - test
    - code_quality
    - package
    - deploy

code_quality:
  image: ubuntu:latest
  stage: code_quality
  variables:
    UPLOAD_QUALITY_REPORT: 'curl -X PUT -H "Authorization: Token $QSCORED_API_KEY" -H "repository-link: $CI_PROJECT_URL" +  -H "username:nl429326@dal.ca" -H "Content-Type: mulitpart/form-data" --url "https://qscored.com/api/upload/file.xml?is_open_access=off&version=$CI_PIPELINE_IID&project_name=ci-demo" -F "file=@Designite_output/DesigniteAnalysis.xml"'
  before_script:
    - apt-get update
    - ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone
    - apt-get --yes --force-yes install wget curl maven git
  script:
    - wget -O DesigniteJava.jar https://www.dropbox.com/s/mwizkj8uhplz4x3/DesigniteJava.jar?dl=1
    - java --version
    - echo $CI_PROJECT_PATH
    # - java -jar DesigniteJava.jar -ci -repo $CI_PROJECT_PATH -pat $PAT -host "git.cs.dal.ca"
  #  - java -jar DesigniteJava.jar -i . -o "Designite_output"
    - java -jar DesigniteJava.jar -i . -o Designite_output -f XML
    - 'eval "$UPLOAD_QUALITY_REPORT"'

build_job:
  stage: build
  script:
    - mvn compile
  tags:
    - ugrad

test_job:
  stage: test
  script:
    - mvn test
  tags:
    - ugrad
  artifacts:
    when : always 
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml  
  
package_job:
  stage : package
  script: mvn package
  artifacts: 
    paths:
      - target/*.jar

# ref : https://linuxize.com/post/how-to-use-scp-command-to-securely-transfer-files/

deploy_job_stage_environment:
  image: ruby:latest
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
    - export HEROKU_API_KEY=$HEROKU_APIKEY
    - heroku run --app $HEROKU_APPNAME migrate
  environment:
    name: development
    url: $HEROKU_APP_HOST
  after_script:
    - echo "Deploy complete!"

